# One CLI to format the code tree - https://github.com/numtide/treefmt

[formatter.python]
# Formatter to run
command = "ruff"
# Command-line arguments for the command
options = ["format"]
# Glob pattern of files to include
includes = [ "*.py" ]
# Glob patterns of files to exclude
excludes = []
